### ISSUE TITLE
Intermittent crash or bad data with Numo::Pocketfft 0.2.1

### ISSUE THREAD

**Issue by mike-bourgeous** [yoshoku/numo-pocketfft#3]
First of all, thanks for making Numo::Pocketfft.  I'm really glad that Numo::Pocketfft provides an alternative to using FFTW and FFTE.  I'm using it in this project: https://github.com/mike-bourgeous/mb-sound

While testing some new code, I found that sometimes Numo::Pocketfft either produces unexpected results, or causes a segmentation fault.  It seems like this mostly happens with larger inputs, including 3 and 4 dimensional inputs.  But sometimes everything works fine.

## Test results

A successful run:

```bash
$ bin/reproduce_pocket_fft_crash.rb     
1 dimensions
Small 10
Large 64
4 dimensions
Small 10000
Large 16777216
3 dimensions
Small 1000
Large 262144
2 dimensions
Small 100
Large 4096
```

Unexpected data (0 DC for an array filled with 1):

```bash
$ bin/reproduce_pocket_fft_crash.rb 
1 dimensions
Small 10
Large 64
4 dimensions
Small 10000
Large 16777216
3 dimensions
Small 1000
Large 262144
Traceback (most recent call last):
        3: from bin/reproduce_pocket_fft_crash.rb:29:in `<main>'
        2: from bin/reproduce_pocket_fft_crash.rb:29:in `each'
        1: from bin/reproduce_pocket_fft_crash.rb:46:in `block in <main>'
bin/reproduce_pocket_fft_crash.rb:15:in `assert': Expected 1, got 0.0 (RuntimeError)
```

Crash:

```bash
$ bin/reproduce_pocket_fft_crash.rb 
1 dimensions
Small 10
Large 64
4 dimensions
Small 10000
Large 16777216
3 dimensions
Small 1000
Large 262144
/home/nitrogen/.rvm/gems/ruby-2.7.2@mb-rb-sound/gems/numo-pocketfft-0.2.1/lib/numo/pocketfft.rb:231: [BUG] Segmentation fault at 0x00007fe6aa523010
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0010 p:---- s:0054 e:000053 CFUNC  :ext_cfft
c:0009 p:0179 s:0049 e:000048 METHOD /home/nitrogen/.rvm/gems/ruby-2.7.2@mb-rb-sound/gems/numo-pocketfft-0.2.1/lib/numo/pocketfft.rb:231
c:0008 p:0012 s:0036 e:000035 BLOCK  /home/nitrogen/.rvm/gems/ruby-2.7.2@mb-rb-sound/gems/numo-pocketfft-0.2.1/lib/numo/pocketfft.rb:68 [FINISH]
c:0007 p:---- s:0032 e:000031 CFUNC  :each
c:0006 p:0075 s:0028 e:000027 METHOD /home/nitrogen/.rvm/gems/ruby-2.7.2@mb-rb-sound/gems/numo-pocketfft-0.2.1/lib/numo/pocketfft.rb:68
c:0005 p:0039 s:0022 e:000021 METHOD bin/reproduce_pocket_fft_crash.rb:25
c:0004 p:0222 s:0017 e:000015 BLOCK  bin/reproduce_pocket_fft_crash.rb:46 [FINISH]
c:0003 p:---- s:0010 e:000009 CFUNC  :each
c:0002 p:0029 s:0006 e:000005 EVAL   bin/reproduce_pocket_fft_crash.rb:29 [FINISH]
c:0001 p:0000 s:0003 E:001f20 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
bin/reproduce_pocket_fft_crash.rb:29:in `<main>'
bin/reproduce_pocket_fft_crash.rb:29:in `each'
bin/reproduce_pocket_fft_crash.rb:46:in `block in <main>'
bin/reproduce_pocket_fft_crash.rb:25:in `fft'
/home/nitrogen/.rvm/gems/ruby-2.7.2@mb-rb-sound/gems/numo-pocketfft-0.2.1/lib/numo/pocketfft.rb:68:in `fftn'
/home/nitrogen/.rvm/gems/ruby-2.7.2@mb-rb-sound/gems/numo-pocketfft-0.2.1/lib/numo/pocketfft.rb:68:in `each'
/home/nitrogen/.rvm/gems/ruby-2.7.2@mb-rb-sound/gems/numo-pocketfft-0.2.1/lib/numo/pocketfft.rb:68:in `block in fftn'
/home/nitrogen/.rvm/gems/ruby-2.7.2@mb-rb-sound/gems/numo-pocketfft-0.2.1/lib/numo/pocketfft.rb:231:in `raw_fft'
/home/nitrogen/.rvm/gems/ruby-2.7.2@mb-rb-sound/gems/numo-pocketfft-0.2.1/lib/numo/pocketfft.rb:231:in `ext_cfft'

-- Machine register context ------------------------------------------------
 RIP: 0x00007fe6e80b57e0 RBP: 0x0000000000000400 RSP: 0x00007ffd978052c8
 RAX: 0x00007fe6aa122010 RBX: 0x00007fe6aa122010 RCX: 0x0000000000000000
 RDX: 0x0000000000000400 RDI: 0x00007fe6aa122010 RSI: 0x00007fe6aa523010
  R8: 0x00007fe6aa122010  R9: 0x0000000000000000 R10: 0x0000000000000022
 R11: 0x0000000000000206 R12: 0x000055af46f0b1e0 R13: 0x00007fe6aa523010
 R14: 0x00000000011b5c89 R15: 0x000055af46d13c38 EFL: 0x0000000000010287

-- C level backtrace information -------------------------------------------
/home/nitrogen/.rvm/rubies/ruby-2.7.2/lib/libruby.so.2.7(rb_vm_bugreport+0x573) [0x7fe6e83ffd53] vm_dump.c:755
[0x7fe6e8222f9b]
/home/nitrogen/.rvm/rubies/ruby-2.7.2/lib/libruby.so.2.7(sigsegv+0x4d) [0x7fe6e835c5cd] signal.c:946
/lib/x86_64-linux-gnu/libc.so.6(0x7fe6e7f6d210) [0x7fe6e7f6d210]
[0x7fe6e80b57e0]
/home/nitrogen/.rvm/gems/ruby-2.7.2@mb-rb-sound/gems/numo-pocketfft-0.2.1/lib/numo/pocketfft/pocketfftext.so(numo_pocketfft_fft+0x350) [0x7fe6e41930f0] /usr/include/x86_64-linux-gnu/bits/string_fortified.h:34
/home/nitrogen/.rvm/gems/ruby-2.7.2@mb-rb-sound/gems/numo-pocketfft-0.2.1/lib/numo/pocketfft/pocketfftext.so(numo_pocketfft_fft) (null):0
```

## Script to reproduce

Here is a script that reproduces the issue on my system, with Ruby 2.7.2 and Numo::Narray version 0.9.1.9:

```ruby
#!/usr/bin/env ruby

require 'bundler/setup'
require 'numo/pocketfft'

def dc_input_small(ndim)
  Numo::DFloat.ones(*([10] * ndim))
end

def dc_input_large(ndim)
  Numo::DFloat.ones(*([64] * ndim))
end

def assert(value, expected)
  raise "Expected #{expected}, got #{value}" if value != expected
end

def fft(data)
  case data.ndim
  when 1
    Numo::Pocketfft.fft(data) / data.length
  when 2
    Numo::Pocketfft.fft2(data) / data.length
  else
    Numo::Pocketfft.fftn(data) / data.length
  end
end

[1, 4, 3, 2].each do |ndim|
  puts "#{ndim} dimensions"

  dc1 = dc_input_small(ndim)
  dc2 = dc_input_large(ndim)

  puts "Small #{dc1.length}"

  assert(fft(dc1)[*([0] * ndim)].real.round(5), 1)
  assert(fft(dc1)[*([1] * ndim)].real.round(5), 0)
  assert(fft(dc1)[*([0] * ndim)].imag.round(5), 0)
  assert(fft(dc1)[*([1] * ndim)].imag.round(5), 0)
  assert(fft(dc1).sum.real.round(5), 1)
  assert(fft(dc1).sum.imag.round(5), 0)

  puts "Large #{dc2.length}"

  assert(fft(dc2)[*([0] * ndim)].real.round(5), 1)
  assert(fft(dc2)[*([1] * ndim)].real.round(5), 0)
  assert(fft(dc2)[*([0] * ndim)].imag.round(5), 0)
  assert(fft(dc2)[*([1] * ndim)].imag.round(5), 0)
  assert(fft(dc2).sum.real.round(5), 1)
  assert(fft(dc2).sum.imag.round(5), 0)
end
```

**Comment by yoshoku** [comment]
@mike-bourgeous 
Thank you for the detail report. I have released a new version with bugfix.
https://rubygems.org/gems/numo-pocketfft/versions/0.2.2

**Comment by mike-bourgeous** [comment]
@yoshoku Thanks!  I have verified that 0.2.2 fixes the issue on my system.
